version: '3.7'
services:
  db:
    image: mysql:8.0.17
    command: mysqld --default-authentication-plugin=mysql_native_password
    volumes:
      - ./docker/for_dev/db/store:/var/lib/mysql
      - ./docker/for_dev/db/log:/var/log/mysql
      - ./docker/for_dev/db/my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - TZ=UTC
