default: &default
  adapter: mysql2
  encoding: utf8mb4
  charset: utf8mb4
  collation: utf8mb4_bin
  username: <%= ENV['DB_USER'] || 'root' %>
  password: <%= ENV['DB_PSWD'] || 'root' %>
  host: <%= ENV['DB_HOST'] || '127.0.0.1' %>
  port: <%= ENV['DB_PORT'] || 3306 %>
  pool: <%= ENV['RAILS_MAX_THREADS'] || 5 %>
  timeout: 5000

development:
  <<: *default
  database: workshop_dev

test:
  <<: *default
  database: workshop_test

production:
  <<: *default
  database: workshop_prd

