name: Rubocop & ESLint checks
on: [pull_request]
jobs:
  lint:
    name: Lint

    runs-on: ubuntu-latest

    strategy:
      matrix:
        ruby: ['2.6.x']

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Ruby version
        uses: actions/setup-ruby@master
        with:
          ruby-version: ${{ matrix.ruby }}

      - name: apt-get
        run: |
          sudo apt-get update
          sudo apt-get install libmysqlclient-dev

      - name: Set up bundler
        run: gem install bundler

      - name: Cache gems
        uses: actions/cache@preview
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gem-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gem-

      - name: Cache node modules
        uses: actions/cache@preview
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: bundle install
        run: bundle install --path vendor/bundle

      - name: yarn install
        run: yarn install

      - name: Rubocop checks
        run: bundle exec rubocop

      - name: Typescript checks
        run: yarn run typecheck

      - name: ESlint checks
        run: yarn run lint

      - name: Run jest
        run: yarn run jest
